name: .NET Standard

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  NetStd-CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: .\scripts\netstd\build.ps1
      shell: pwsh
    - name: Test
      run: .\scripts\netstd\test.ps1
      shell: pwsh
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
          name: Output
          path: CilTools.Metadata/bin/Debug/
