name: .NET Standard

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  NetStd-CI:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.300'
    - name: Build with dotnet
      run: dotnet build CilTools.Metadata/CilTools.Metadata.csproj -f netstandard2.0
    - name: Build tests with dotnet
      run: dotnet build tests/CilTools.BytecodeAnalysis.Tests.NetCore/CilTools.BytecodeAnalysis.Tests.NetCore.csproj
    - name: Test
      run: dotnet test tests/CilTools.BytecodeAnalysis.Tests.NetCore/CilTools.BytecodeAnalysis.Tests.NetCore.csproj
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
          name: Output
          path: CilTools.Metadata/bin/Debug/
