name: .NET Standard

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  NetStd-CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build CilTools.Metadata/CilTools.Metadata.csproj -f netstandard2.0
    - name: Build tests with dotnet
      run: dotnet build tests/CilTools.BytecodeAnalysis.Tests/CilTools.BytecodeAnalysis.Tests.csproj -f netcoreapp3.1
    - name: Build CommandLine with dotnet
      run: dotnet build tests/CilTools.CommandLine.Tests/CilTools.CommandLine.Tests.csproj
    - name: Build CilView.Core with dotnet
      run: dotnet build tests/CilView.Tests/CilView.Tests.csproj
    - name: Test
      run: dotnet test tests/CilTools.BytecodeAnalysis.Tests/CilTools.BytecodeAnalysis.Tests.csproj -f netcoreapp3.1
    - name: Test CommandLine
      run: dotnet test tests/CilTools.CommandLine.Tests/CilTools.CommandLine.Tests.csproj
    - name: Test CilView.Core
      run: dotnet test tests/CilView.Tests/CilView.Tests.csproj -f netcoreapp3.1
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
          name: Output
          path: CilTools.Metadata/bin/Debug/
